### ISSUE TITLE
Android 12 下载失败

### ISSUE THREAD

**Issue by ByXLL** [fly-studio/douyin-downloader#14]
Android 12 系统，下载失败
W/System.err: java.io.IOException: Operation not permitted
        at java.io.UnixFileSystem.createFileExclusively0(Native Method)
        at java.io.UnixFileSystem.createFileExclusively(UnixFileSystem.java:317)
        at java.io.File.createTempFile(File.java:2007)
        at com.fly.video.downloader.util.io.FileStorage.createTempFile(FileStorage.java:52)
        at com.fly.video.downloader.util.network.DownloaderTask.doInBackground(DownloaderTask.java:45)
        at com.fly.video.downloader.util.network.DownloaderTask.doInBackground(DownloaderTask.java:23)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

**Comment by ByXLL** [comment]
抖音

**Comment by fly-studio** [comment]
已经修复android 11+
